CXX=            g++
CXXFLAGS=       -g -Wall -std=gnu++11
SHELL=  		bash

all:			greatest_common_divisor

greatest_common_divisor:	greatest_common_divisor.cpp
	$(CXX) $(CXXFLAGS) -o $@ $^

clean:
	rm -f greatest_common_divisor
